### ISSUE TITLE
How to write to YAML file?

### ISSUE THREAD

**Issue by JeffHD** [Maikuolan/Common#11]
How do i edit a YAML file?

I have tried: $Object->Data['foo'] = 'bar';

but it dont work for me.

**Comment by Maikuolan** [comment]
Hi @JeffHD,

You can reconstruct the object's internal data array back into raw YAML data by using the reconstruct method. :-)

*Documentation: [Can the reverse be done, too? Can an array be converted into YAML data?](https://github.com/Maikuolan/Common/blob/v2/_docs/YAML.md#can-the-reverse-be-done-too-can-an-array-be-converted-into-yaml-data)*

As a complete example, let's say if we have a YAML file, containing this:

```YAML
String foo: "Bar"
Integer foo: 1234
Float foo: 123.4
Example numeric array:
 - "Bar1"
 - "Bar2"
 - "Bar3"
 - "Bar4"
 ```

If we wanted to change `Integer foo` from `1234` to `5678`:

```PHP
$OldData = file_get_contents('example.yaml');
$Object = new \Maikuolan\Common\YAML($OldData);
$Object->Data['Integer foo'] = 5678;
$NewData = $Object->reconstruct($Object->Data);
file_put_contents('example.yaml', $NewData);
```
